# Generated by Django 4.0.1 on 2022-01-20 04:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Barang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_number', models.CharField(max_length=18, unique=True)),
                ('description', models.CharField(max_length=32)),
                ('color_code', models.CharField(max_length=6, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RencanaProduksi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_rencana', models.IntegerField()),
                ('tanggal', models.DateTimeField()),
                ('qty', models.IntegerField()),
                ('status', models.CharField(choices=[('A', 'Active'), ('C', 'Canceled')], default='A', max_length=1)),
                ('part_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recordproduksi.barang')),
            ],
        ),
        migrations.CreateModel(
            name='HasilProduksi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField()),
                ('timestamp', models.TimeField()),
                ('status', models.CharField(choices=[('OKD', 'OK Direct'), ('OKB1', 'OK Buffing Bintik'), ('OKB2', 'OK Buffing OP'), ('OKB3', 'OK Buffing Dirty'), ('OKB4', 'OK Buffing Dent'), ('OKB5', 'OK Buffing Scratch'), ('NG1', 'NG Barry'), ('NG2', 'NG Sagging'), ('NG3', 'NG Crater'), ('NG4', 'NG Tipis'), ('NG5', 'NG Serat'), ('NG6', 'NG Pop')], default='OKD', max_length=4)),
                ('id_rencana_produksi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recordproduksi.rencanaproduksi')),
                ('part_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recordproduksi.barang')),
            ],
        ),
    ]
