# Generated by Django 4.0.1 on 2022-01-24 03:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recordproduksi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rencanaproduksi',
            name='part_number',
        ),
        migrations.RemoveField(
            model_name='rencanaproduksi',
            name='qty',
        ),
        migrations.AlterField(
            model_name='rencanaproduksi',
            name='tanggal',
            field=models.DateTimeField(),
        ),
        migrations.CreateModel(
            name='RencanaProduksiDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_number', models.IntegerField(max_length=2)),
                ('qty', models.IntegerField()),
                ('part_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recordproduksi.barang')),
                ('rencana_produksi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='recordproduksi.rencanaproduksi')),
            ],
        ),
    ]
