# Generated by Django 4.0.1 on 2022-01-24 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recordproduksi', '0003_rename_id_rencana_produksi_hasilproduksi_rencana_produksi_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hasilproduksi',
            name='status',
        ),
        migrations.AddField(
            model_name='hasilproduksidetail',
            name='status',
            field=models.CharField(choices=[('OKD', 'OK Direct'), ('OKB1', 'OK Buffing Bintik'), ('OKB2', 'OK Buffing OP'), ('OKB3', 'OK Buffing Dirty'), ('OKB4', 'OK Buffing Dent'), ('OKB5', 'OK Buffing Scratch'), ('NG1', 'NG Barry'), ('NG2', 'NG Sagging'), ('NG3', 'NG Crater'), ('NG4', 'NG Tipis'), ('NG5', 'NG Serat'), ('NG6', 'NG Pop')], default='OKD', max_length=4),
        ),
    ]
